# Generated by Django 4.2.7 on 2024-01-07 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbill.billing')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_prescribed', models.DateField()),
                ('prescribing_doctor', models.CharField(max_length=100)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BillingRecord',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(default='DEFAULT_BATCH', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_of_manufacture',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 7, 6)),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturer',
            field=models.CharField(default='not entered', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='medicine_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('vial', 'Vial'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drop', 'Drop'), ('powder', 'Powder'), ('cream', 'Cream'), ('gel', 'Gel'), ('liquid', 'Liquid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbill.medicine'),
        ),
        migrations.AddField(
            model_name='billing',
            name='medicines',
            field=models.ManyToManyField(through='medbill.BillingItem', to='medbill.medicine'),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbill.patient'),
        ),
    ]
