# Generated by Django 4.2.7 on 2024-01-16 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0002_alter_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
    ]
