# Generated by Django 4.2.7 on 2024-01-13 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0002_billing_billingitem_medicine_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 7, 11)),
        ),
    ]
