# Generated by Django 4.2.7 on 2024-01-13 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0003_alter_billing_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 7, 12)),
        ),
    ]
