# Generated by Django 4.2.7 on 2024-01-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0004_alter_inventoryitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='medicines',
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbill.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='medicine_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
