# Generated by Django 4.2.7 on 2024-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0006_inventoryitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
