# Generated by Django 4.2.7 on 2024-01-16 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0007_billing_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(default='not enterd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 7, 14)),
        ),
    ]
