# Generated by Django 4.2.7 on 2024-01-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0003_alter_inventoryitem_expiry_date'),
        ('medbill', '0008_billing_invoice_number_billingitem_invoice_number_and_more'),
    ]

    operations = [
    ]
