# Generated by Django 4.2.7 on 2024-02-03 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0009_merge_20240117_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
    ]
