# Generated by Django 4.2.7 on 2024-02-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0010_notification_alter_billingitem_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medbill.inventoryitem'),
        ),
    ]
