# Generated by Django 4.2.7 on 2024-02-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0011_notification_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='medicine',
        ),
    ]
