# Generated by Django 4.2.7 on 2024-02-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbill', '0012_remove_notification_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medbill.inventoryitem')
        ),
    ]

    